### PR TITLE
Surface Fees and FeeReferences

### PR DESCRIPTION
**Pull request by ajsteadly**

### CODE REVIEW

**Comment by ajsteadly** [comment]
Example:

```
from analyzere import (
    Fee,
    FeeReference,
    Layer
)
from datetime import datetime, timezone


fee1_ref = FeeReference(ref=['layer', 'fees', 'MyFee1'])
fee2_ref = FeeReference.create_from_fee_name('MyFee2')

my_fee = Fee(type='ProportionalExpense',
             name='MyBestFee',
             payout_date=datetime(2017, 1, 23, 4, 0, 0, tzinfo=timezone.utc),
             rate=0.04,
             fees=[fee1_ref, fee2_ref],
             premiums=[FeeReference.PREMIUM])

layer = Layer(type='CatXL',
              fees=[my_fee])
```

**Comment by hanz-analyzere** [comment]
I think there should be a way to create a `FeeReference` from a `Fee` object. (Besides just fetching its name.) I don't see something like that here.

**Comment by ajsteadly** [comment]
New example:
```
from analyzere import (
    Fee,
    FeeReference,
    Layer,
    MonetaryUnit
)
from datetime import datetime, timezone

fee1_ref = FeeReference(ref=['layer', 'fees', 'MyFee1'])
fee2_ref = FeeReference.create_from_fee_name('MyFee2')

fee3 = Fee(type='FixedExpense',
           payout_date=datetime(2017, 5, 13, 0, 0, 0, tzinfo=timezone.utc),
           amount=MonetaryUnit(3250, 'USD'))

fee3_ref = FeeReference.create_from_fee(fee3)

my_fee = Fee(type='ProportionalExpense',
             name='MyBestFee',
             payout_date=datetime(2017, 1, 23, 4, 0, 0, tzinfo=timezone.utc),
             rate=0.04,
             fees=[fee1_ref, fee2_ref, fee3_ref],
             premiums=[FeeReference.PREMIUM])

layer = Layer(type='CatXL',
              fees=[my_fee])
```

If the supplied fee object has no `name`, you get `AttributeError: 'Fee' object has no attribute 'name'`. @hanz-analyzere is it worth wrapping this error?

**Comment by hanz-analyzere** [comment]
@ajsteadly I think that should be fine.

**Comment by ajsteadly** [comment]
I dropped `create_` and added a `ref()` method on fee objects.

**Pull request merged**
