### PR TITLE
ARE-5905: surface layer policy to python client

### PR DESCRIPTION
**Pull request by Fishflavored**

### CODE REVIEW

**Comment by Fishflavored** [comment]
retest this please

**Comment by mcgillij** [comment]
I'll have a PR in a second to fix the wrong version of pip being installed. There's some flake8 issues with some of the file's that I'm passing in as well.

**Comment by mcgillij** [comment]
OMG you didn't use a fork!

**Comment by mcgillij** [comment]
I'll rebuild the PR :)

**Comment by Fishflavored** [comment]
ahh.. sorry.. I will make a fork now, forget to make a fork for python repo~~~

**Comment by Fishflavored** [comment]
Demo'd to @neil-b

**Pull request merged**
